### ISSUE TITLE
Adding to modpack

### ISSUE THREAD

**Issue by itsdinkd** [xienaoban/minecraft-bole#21]
Hello, I am the creator of Another Quality Modpack 2 https://www.curseforge.com/minecraft/modpacks/another-quality-modpack-2 

I would love to add your mod, however, my pack idea is about removing all OP things. I can see in the handbook, and the offered features that you can set things to invulnerable, get spawn eggs, highlight entities using glow, restock villagers, and other features that would be considered 'cheats' or features that should not be on a server ( A lot of people host my modpack on servers) 

If you can add into the config a way to disable the more 'cheating' features, I will be more than excited and grateful to add this mod. it's amazing.

**Comment by xienaoban** [comment]
You don't have to~

**Comment by xienaoban** [comment]
`invulnerable`, `get spawn eggs` are only available in creative mode, and you need to pay emeralds to use `restock`. So it won't be too OP (in my opinion).

But It's a reasonable request to let the server to ban some features. I'll take it into consideration but I can't guarantee when this requirement will be done.

**Comment by xienaoban** [comment]
How about just adding a blacklist and features in this blacklist are for preview only.

**Comment by itsdinkd** [comment]
Sounds good!

**Comment by xienaoban** [comment]
@itsdinkd Now you can ban any request you don't want on server side.
![2022-05-22_13 12 54](https://user-images.githubusercontent.com/22251525/169679906-55123825-095e-4cb4-97bf-5785a71a0c9e.png)
