### ISSUE TITLE
Conflicts with REI

### ISSUE THREAD

**Issue by itsdinkd** [xienaoban/minecraft-bole#22]
I would suggest adding a way to 'hide' Rouhgly Enough Items when using the book 

![image](https://user-images.githubusercontent.com/35115304/168450776-baf58977-d425-420d-b62d-f513bf7aa093.png)

**Comment by xienaoban** [comment]
Fixed. REI GUI is no longer displayed over bole screens now.
I'll publish a new version later as there is some other work to be done.
