### ISSUE TITLE
/give item writable book request

### ISSUE THREAD

**Issue by Afrocntrik** [xienaoban/minecraft-bole#26]
You stated the handbook utilizes nbt data but I am utilizing a nbt editor and due to the unique characters in the data itself I'm unable to generate the book other than creative and the wandering trader. I was hoping to give it to the player on spawn for my pack. Any help would be great.

**Comment by Afrocntrik** [comment]
[{Count:1b,id:"minecraft:writable_book",tag:{CustomModelData:14489768,bole_handbook:"1.1.0-mc1.19-fabric",display:{Lore:['{"translate": "description.bole.bole_handbook", "color": "dark_aqua", "italic": false}'],Name:'{"translate": "title.bole.bole_handbook", "color": "aqua", "bold": true, "italic": false}'},pages:["§lMod name: §2§lBole

§r§0It means that you have not installed the mod `Bole` if you see this text. You may download this mod at:

Curseforge: §9§nhttps://www.curseforge.com/minecraft/mc-mods/bole
"]}}] this is the raw nbt

**Comment by xienaoban** [comment]
Do you mean the char “§”？They are [formatting codes](https://minecraft.fandom.com/wiki/Formatting_codes) (or color codes). I use them to change the text color. You can delete the codes if you are not able to input them.

**Comment by xienaoban** [comment]
By the way this mod supports hot key. You can turn it on in the option screen of the mod. So you can open the bole screen by hotkey and don’t need a handbook item.
