### ISSUE TITLE
Command errors after adding mods that have new mobs 

### ISSUE THREAD

**Issue by Afrocntrik** [xienaoban/minecraft-bole#27]
Logs with mods and errors during testing:
[2022-07-25-3.log](https://github.com/xienaoban/minecraft-bole/files/9183990/2022-07-25-3.log)
[2022-07-25-4.log](https://github.com/xienaoban/minecraft-bole/files/9183991/2022-07-25-4.log)

Log after mob mods were disabled:
[latest.log](https://github.com/xienaoban/minecraft-bole/files/9183998/latest.log)
After disabling the mods that added new mobs I was able to input a command but before hand I got an error looking like this as well as the Bole book directory would not open utilizing the hotkey. Also was previously tested by removing Bole and the error was resolved. 

![2022-07-25_14 52 08](https://user-images.githubusercontent.com/11052983/180855863-fce7901e-1b22-40cd-95e0-6b4051f503c4.png)

**Comment by xienaoban** [comment]
Hi. There are so many mods in your log. Which one is the mod that adds more mobs? Maybe I should debug locally.

**Comment by xienaoban** [comment]
Also, what does the command in your screenshot do (what is your command)?

**Comment by xienaoban** [comment]
Fixed. I'll release a new version later.
